# Exercise 1: Data cleaning

Before doing actual data analysis, we usually first need to clean the data.
This might involve steps such as dealing with missing values and encoding categorical variables as integers.
In this exercise, you will perform such steps based on the Titanic passenger data.

1. Load the Titanic data set in `titanic.csv` located in the `data/` folder.
2. Report the number of observations with missing `Age`, for example using
   [`isna()`](https://pandas.pydata.org/docs/reference/api/pandas.isna.html).
3. Compute the average age in the data set. Use the following approaches and compare your results:
    1.  Use pandas's
        [`mean()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.mean.html)
        method.
    2.  Convert the `Age` column to a NumPy array using
        [`to_numpy()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html).
        Experiment with NumPy's
        [`np.mean()`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)
        and
        [`np.nanmean()`](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html)
        to see if you obtain the same results.
4. Replace all missing ages with the mean age you computed above, rounded to the
   nearest integer.
   Note that in "real" applications, replacing missing values with sample means is usually not a good idea.
   Convert this updated `Age` column to integer type using
   [`astype()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.astype.html).

   *Hint:* Use `astype(int)`.

5. Generate a new column `Female` which takes on the value one if `Sex` is equal to `"female"` and zero otherwise.
   This is called an _indicator_ or _dummy_ variable, and is useful for numerical
   analysis or regression.
   Delete the original column `Sex`.
6. Save your cleaned data set as `titanic-clean.csv` using
   [`to_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)
   with `,` as the field separator.
   Tell `to_csv()` to *not* write the `DataFrame` index to the CSV file as it's not needed in this example.

In [ ]:
import pandas as pd
import numpy as np

DATA_PATH = '../../data'
file = f'{DATA_PATH}/titanic.csv'
data = pd.read_csv(file)
data

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q

In [3]:
data['Age'].isna().sum()

np.int64(177)

In [21]:
mean_age = data['Age'].mean()

age = data['Age'].to_numpy()
print(np.mean(age))
print(np.nanmean(age))

29.758888888888887
29.758888888888887

In [20]:
mean_age = np.round(mean_age)

is_missing = data['Age'].isna()

data.loc[is_missing, 'Age'] = mean_age

data['Age'].astype(int)

0      22
1      38
2      26
3      35
4      35
       ..
886    27
887    19
888    30
889    26
890    32
Name: Age, Length: 891, dtype: int64

In [25]:
is_female = data['Sex'] == 'female'
data['Female'] = is_female.astype(int)
del data['Sex']
data

,PassengerId,Survived,Pclass,Name,Age,Ticket,Fare,Cabin,Embarked,Female
0,1,0,3,"Braund, Mr. Owen Harris",22.0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss Laina",26.0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",35.0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss Margaret Edith",19.0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",30.0,W./C. 6607,23.4500,NaN,S,1
889,890,1,1,"Behr, Mr. Karl Howell",26.0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",32.0,370376,7.7500,NaN,Q,0

In [27]:
data.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Age          891 non-null    float64
 5   Ticket       891 non-null    str
 6   Fare         891 non-null    float64
 7   Cabin        204 non-null    str
 8   Embarked     889 non-null    str
 9   Female       891 non-null    int64
dtypes: float64(2), int64(4), str(4)
memory usage: 69.7 KB

In [28]:
file_clean = f'{DATA_PATH}/titanic-clean.csv'

data.to_csv(file_clean, sep=',', index=False)

***
# Exercise 2: Selecting subsets of data

In this exercise, you are asked to select subsets of macroeconomic data for the United States based on some criteria.

1.  Load the annual data from FRED which are located in `FRED_annual.xlsx`
    in the `data/FRED` folder.

2.  Print the list of columns and the number of non-missing observations.

3.  Since we are dealing with time series data, set the column `Year` as the `DataFrame`
    index.

4.  Print all observations for the 1960s decade using at least two different methods.

5.  Using the data in the column `GDP`, compute the annual GDP growth in percent and store it in the column `GDP_growth`. Select the years in which

    1.  GDP growth was above 5%.
    2.  GDP growth was negative, but inflation was still above 5% (such episodes are called "stagflation" since usually negative GDP growth is associated with low inflation).

        Use at least two methods for the stagflation selection.

    *Hint:* You can compute changes relative to the previous observation using the
    [`pct_change()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.pct_change.html)
    method.

In [32]:
# Part 1
file = f'{DATA_PATH}/FRED/FRED_annual.xlsx'
df = pd.read_excel(file)
df.head(3)

   Year     GDP   CPI  UNRATE  FEDFUNDS  INFLATION
0  1954  2877.7  26.9     5.6       1.0        NaN
1  1955  3083.0  26.8     4.4       1.8  -0.371747
2  1956  3148.8  27.2     4.1       2.7   1.492537

In [35]:
# Part 2
df.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Year       72 non-null     int64
 1   GDP        72 non-null     float64
 2   CPI        72 non-null     float64
 3   UNRATE     72 non-null     float64
 4   FEDFUNDS   72 non-null     float64
 5   INFLATION  71 non-null     float64
dtypes: float64(5), int64(1)
memory usage: 3.5 KB

In [48]:
# Part 3

df = df.set_index('Year')

In [49]:
# Part 4
df.loc[1960:1969]

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION
Year
1960  3500.3  29.6     5.5       3.2   1.369863
1961  3590.1  29.9     6.7       2.0   1.013514
1962  3810.1  30.3     5.6       2.7   1.337793
1963  3976.1  30.6     5.6       3.2   0.990099
1964  4205.3  31.0     5.2       3.5   1.307190
1965  4478.6  31.5     4.5       4.1   1.612903
1966  4773.9  32.5     3.8       5.1   3.174603
1967  4904.9  33.4     3.8       4.2   2.769231
1968  5145.9  34.8     3.6       5.7   4.191617
1969  5306.6  36.7     3.5       8.2   5.459770

In [52]:
# Still part 4
df.query('Year >= 1960 & Year <= 1969')

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION
Year
1960  3500.3  29.6     5.5       3.2   1.369863
1961  3590.1  29.9     6.7       2.0   1.013514
1962  3810.1  30.3     5.6       2.7   1.337793
1963  3976.1  30.6     5.6       3.2   0.990099
1964  4205.3  31.0     5.2       3.5   1.307190
1965  4478.6  31.5     4.5       4.1   1.612903
1966  4773.9  32.5     3.8       5.1   3.174603
1967  4904.9  33.4     3.8       4.2   2.769231
1968  5145.9  34.8     3.6       5.7   4.191617
1969  5306.6  36.7     3.5       8.2   5.459770

In [53]:
# Part 5

df['GDP_growth'] = df['GDP'].pct_change() * 100

df.query('GDP_growth > 5')

          GDP    CPI  UNRATE  FEDFUNDS  INFLATION  GDP_growth
Year
1955   3083.0   26.8     4.4       1.8  -0.371747    7.134170
1959   3412.4   29.2     5.4       3.3   1.038062    6.931562
1962   3810.1   30.3     5.6       2.7   1.337793    6.127963
1964   4205.3   31.0     5.2       3.5   1.307190    5.764443
1965   4478.6   31.5     4.5       4.1   1.612903    6.498942
1966   4773.9   32.5     3.8       5.1   3.174603    6.593578
1972   5780.0   41.8     5.6       4.4   3.209877    5.255490
1973   6106.4   44.4     4.9       8.7   6.220096    5.647059
1976   6387.4   56.9     7.7       5.0   5.762082    5.386989
1978   7052.7   65.2     6.1       7.9   7.590759    5.535105
1984   8195.3  103.9     7.5      10.2   4.317269    7.236042
2021  21532.4  271.0     5.4       0.1   4.673619    6.151988

In [54]:
# Still part 5
df.query('GDP_growth < 0 & INFLATION > 5')

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION  GDP_growth
Year
1974  6073.4  49.3     5.6      10.5  11.036036   -0.540417
1975  6060.9  53.8     8.5       5.8   9.127789   -0.205816
1980  7257.3  82.4     7.2      13.4  13.498623   -0.257009
1982  7307.3  96.5     9.7      12.3   6.160616   -1.803400

In [55]:
# Still part 5
condition = (df['GDP_growth'] < 0) & (df['INFLATION'] > 5)
df[condition]

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION  GDP_growth
Year
1974  6073.4  49.3     5.6      10.5  11.036036   -0.540417
1975  6060.9  53.8     8.5       5.8   9.127789   -0.205816
1980  7257.3  82.4     7.2      13.4  13.498623   -0.257009
1982  7307.3  96.5     9.7      12.3   6.160616   -1.803400

***
# Exercise 3: Labor market statistics for the US

In this exercise, you are asked to compute some descriptive statistics for the unemployment rate
and the labor force participation rate for the United States. The latter is the
percentage of the civilian noninstitutional population aged 16 and older who are in the
labor force (employed or unemployed). Both rates are expressed as percentages.

1.  Load the monthly time series from FRED which are located in `FRED_monthly.csv`
    in the `data/FRED` folder.

    *Hint:* Use `pd.read_csv(..., parse_dates=['DATE'])` to automatically
    parse strings stored in the `DATE` column as dates.

2.  Print the list of columns and the number of non-missing observations.

3.  Since we are dealing with time series data, set the column `DATE` as the `DataFrame`
    index. Using the date index, select all observations from the first three months
    of the year 2020.

4.  For the columns `UNRATE` (unemployment rate) and `LFPART` (labor force participation rate), compute and report
    the mean, minimum, and maximum values for the whole sample. Round your results
    to one decimal place.

    *Hint:* You can use the `DataFrame` methods
    [`mean()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html),
    [`min()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.min.html), and
    [`max()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.max.html)
    to compute the desired statistics.

    *Hint:* You can use the `DataFrame` method
    [`round()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.round.html)
    to round the results to one decimal place.

5.  You are interested in how the average unemployment rate evolved over the last
    few decades.

    -   Add a new column `Decade` to the `DataFrame` which contains the
        starting year for each decade (e.g., this value should be 1950
        for the years 1950-1959, and so on).

        *Hint:* The decade can be computed from the column `Year` using
        truncated integer division:
        ```python
        df['Year'] // 10 * 10
        ```

    -   Write a loop to compute and report the average unemployment rate (column `UNRATE`)
        for each decade.

        Include only the decades from 1950 to 2010 for which you have all
        observations.

In [72]:
# Part 1
file = f'{DATA_PATH}/FRED/FRED_monthly.csv'
df = pd.read_csv(file, parse_dates=['DATE'])
df.head(3)

        DATE  Year  Month   CPI  UNRATE  FEDFUNDS  REALRATE  LFPART
0 1948-01-01  1948      1  23.7     3.4       NaN       NaN    58.6
1 1948-02-01  1948      2  23.7     3.8       NaN       NaN    58.9
2 1948-03-01  1948      3  23.5     4.0       NaN       NaN    58.5

In [73]:
# Part 2
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 936 entries, 0 to 935
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DATE      936 non-null    datetime64[us]
 1   Year      936 non-null    int64
 2   Month     936 non-null    int64
 3   CPI       935 non-null    float64
 4   UNRATE    935 non-null    float64
 5   FEDFUNDS  858 non-null    float64
 6   REALRATE  528 non-null    float64
 7   LFPART    935 non-null    float64
dtypes: datetime64[us](1), float64(5), int64(2)
memory usage: 58.6 KB

In [74]:
# Part 3
df['DATE'] = pd.to_datetime(df['DATE'])
df = df.set_index('DATE')

In [76]:
df.loc['2020-01-01':'2020-03-31']

            Year  Month    CPI  UNRATE  FEDFUNDS  REALRATE  LFPART
DATE
2020-01-01  2020      1  259.1     3.6       1.6      -0.6    63.3
2020-02-01  2020      2  259.2     3.5       1.6      -0.5    63.3
2020-03-01  2020      3  258.1     4.4       0.6       3.4    62.6

In [78]:
# Part 4
print('Average:')
print(df[['UNRATE', 'LFPART']].mean().round(1))

Average:
UNRATE     5.7
LFPART    62.8
dtype: float64

In [80]:
print('Minimum: ')
print(df[['UNRATE', 'LFPART']].min().round(1))

Minimum:
UNRATE     2.5
LFPART    58.1
dtype: float64

In [81]:
print('Maximum: ')
print(df[['UNRATE', 'LFPART']].max().round(1))

Maximum:
UNRATE    14.8
LFPART    67.3
dtype: float64

In [85]:
# Part 5
df['Decade'] = df['Year'] // 10 * 10
df.head(3)

            Year  Month   CPI  UNRATE  FEDFUNDS  REALRATE  LFPART  Decade
DATE
1948-01-01  1948      1  23.7     3.4       NaN       NaN    58.6    1940
1948-02-01  1948      2  23.7     3.8       NaN       NaN    58.9    1940
1948-03-01  1948      3  23.5     4.0       NaN       NaN    58.5    1940

In [92]:
decade = df.groupby('Decade')
round(decade['UNRATE'].mean(), 1)

Decade
1940    4.9
1950    4.5
1960    4.8
1970    6.2
1980    7.3
1990    5.8
2000    5.5
2010    6.2
2020    4.8
Name: UNRATE, dtype: float64

***
# Exercise 4: Daily stock-market returns

In this exercise, you will compute daily returns for the S&P 500 index and count
trading days with losses or large gains. The column `SP500` contains the index
values.

1.  Load `SP500.csv` from the `data/stockmarket` folder, parse `Date` as dates, and
    set it as the `DataFrame` index. Restrict the data to observations after
    January 1, 2020.

    *Hint:* Use `pd.read_csv(..., parse_dates=['Date'])` to automatically parse the
    strings in the `Date` column as dates.

2.  Compute daily returns in percent using `pct_change()` and store them in a new
    column `Return`. Explain why the first return is missing.

    *Hint:* Multiply the result of `pct_change()` by 100 to express returns in
    percent.

3.  Report the number and percentage of trading days with losses, i.e., negative
    returns. Exclude days with missing returns from the denominator.

    *Hint:* Summing a Boolean `Series` counts the number of `True` values. Use
    `count()` to count nonmissing observations.

4.  Report the number and percentage of trading days with gains of more than 5%.
5.  Report the number and percentage of days with negative returns on both the
    current and the previous trading day. A run of three loss days contributes
    two qualifying days. For the percentage, include only days with both returns
    observed.

    *Hint:* Use `shift()` to obtain the previous trading day's return, and combine
    the two conditions using `&`.

***
# Exercise 5: Working with string data (advanced)

Most of the data we deal with contain strings, i.e., text data (names, addresses, etc.). Often, such data is not in the format needed for analysis, and we have to perform additional string manipulation to extract the exact data we need. This can be achieved using the pandas
[string methods](https://pandas.pydata.org/docs/user_guide/text.html#string-methods).

To illustrate, we use the Titanic data set for this exercise.

1.  Load the Titanic data and restrict the sample to men. (This simplifies the task. Some
    married women's entries contain both their husband's name and their maiden name.)
2.  Print the first five observations of the `Name` column. As you can see, the data is stored in the format _"Last name, Title First name"_ where the title is something like Mr., Rev., etc.
3.  Split the `Name` column by `,` to extract the last name and the remainder as separate columns. You can achieve this using the
   [`partition()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.partition.html)
   string method.
4. Split the remainder (containing the title and first name) using the space
   character `" "` as separator to obtain individual columns for the title and
   the first name.

   *Hint:* The remainder starts with a space after the comma. Use `.str.strip()`
   to remove leading and trailing whitespace before splitting it.

5. Store the three data series in the original `DataFrame` (using the column names `FirstName`, `LastName`, and `Title`) and delete the `Name` column, which is no longer needed.
6. Finally, extract the ship deck from the values in `Cabin`. The ship deck is the first character in the string stored in `Cabin` (A, B, C, ...). You extract the first character using the
   [`get()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.get.html)
   string method. Store the result in the column `Deck`.

*Hint*: pandas's string methods can be accessed using the `.str` attribute. For example,
to partition values in the column `Name`, you need to use
```python
df['Name'].str.partition()
```